spring.application.name=scholar-grid

# Supabase Database Connection
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.xwecbhhgejnoklwnpbub
spring.datasource.password=@PoWeRNIR321@
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings (The Magic)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

google.api.key=${GOOGLE_API_KEY}

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000

spring.config.import=optional:file:.env[.properties]
weather.api.key=cd024ec47d0f4231a8c123503262202
weather.api.url=http://api.weatherapi.com/v1/forecast.json
server.port=8080

supabase.url=https://xwecbhhgejnoklwnpbub.supabase.co/rest/v1/truth_dare_rooms
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3ZWNiaGhnZWpub2tsd25wYnViIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MDU3MzI4OCwiZXhwIjoyMDg2MTQ5Mjg4fQ.HIHVLEItfEkjbLzbfazxB3BjHwe8XHddX-UWEHlMXZM
supabase.bucket.name=ai-resources

telegram.bot.token=8543312045:AAHaY-E866KrEVx8mXw2h9iRp2Y76qZyYb0
telegram.chat.id=-1003770016045

# =============================================
# OPENROUTER API
# =============================================
openrouter.api.key=

openrouter.api.url=https://openrouter.ai/api/v1/chat/completions
openrouter.model=openrouter/free

# =============================================
# GEMINI API
# =============================================


# =============================================
# EMBEDDING MODEL (free, local via Ollama OR OpenRouter)
# =============================================
# Option A: Use OpenRouter for embeddings too
embedding.provider=openrouter
embedding.model=openai/text-embedding-3-small
groq.api.key=
groq.model=llama-3.1-8b-instant

gemini.api.key=
gemini.model=gemini-3-flash-preview
